### ISSUE TITLE
When mRNA is created the label is incorrect as "mRna"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gene-expression-essentials#1]
When mRNA is created it should be properly labelled "mRNA"

**Comment by ariel-phet** [comment]
@AshrafSharf - this is a minor bug in the Java version which should be corrected in the HTML5 port (should involve just modifying the string).

**Comment by AshrafSharf** [comment]
Sure. Will be taken care.

Thanks
Ashraf

**Comment by aadish** [comment]
fixed closing
