### ISSUE TITLE
ribosomes and mRNA destroyers can be led around in some circumstances

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#101]
If a case is set up where mRNA is released near a ribosome or an mRNA destroyer and then picked up and dragged around before the interaction begins, the ribosome or mRNA destroyer will follow the mRNA around as it is being dragged.  Ideally, the connection that was started should be aborted as soon as the mRNA is picked up.

**Comment by jbphet** [comment]
Should now be fixed, will unassign and have this verified on next dev or RC release.

**Comment by phet-steele** [comment]
Looks good.
