### ISSUE TITLE
use a set of SHAs from prior to 11/9/2017 for rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#106]
Today in the status meeting we decided that it was okay to start making changes to chipper for the "chipper:2.0" effort, and this could potentially destabilize the build code.  Therefore, I should use a version of SHAs from prior to that decision point.  At the meeting, I proposed using the SHAs from the recent dev release, but @samreid said I needed to make sure that I included a version of joist with some fixes for the LoL support.  That version is https://github.com/phetsims/joist/commit/ea4290567fa4b04b993bd4f2ba970358a8f3a173, and it is newer than what was included in the recent dev release.  So, the first thing to try will be the SHAs from the dev release with this one updated for joist.  If that doesn't work, I'll need to figure out alternatives.

**Comment by samreid** [comment]
Master is probably safe until Monday (perhaps even beyond Monday), you could take a fresh set of SHAs now, right?

**Comment by jbphet** [comment]
Well, this is what I'm seeing on the automated test report, so I was thinking that the chipper:2.0 train had left the station:

![chipper-test-issues](https://user-images.githubusercontent.com/3082831/32669760-dcc4560a-c5fe-11e7-9875-68229859e33a.PNG)

**Comment by samreid** [comment]
Those problems were not related to chipper (caught in lint rules in other sims):

```
/data/share/phet/continuous-testing/snapshot-1510333835416/curve-fitting/js/curve-fitting/view/CurveNode.js
  1:1  error  Incorrect copyright statement in first comment  copyright

/data/share/phet/continuous-testing/snapshot-1510333835416/plinko-probability/js/common/view/BallsNode.js
  1:1  error  Incorrect copyright statement in first comment  copyright

/data/share/phet/continuous-testing/snapshot-1510333835416/plinko-probability/js/common/view/PegsNode.js
  1:1  error  Incorrect copyright statement in first comment  copyright
```
and they are now resolved in master.

**Comment by jbphet** [comment]
I tested with the SHAs from the most recent dev release (see https://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.13/) with the joist SHA updated to the version identified above.  This worked well in preliminary testing, so this is what has been used for v1.0.0-rc.1.  I'll leave this open for now and will update based on the results of the testing.

**Comment by jbphet** [comment]
This was done, and it worked out well.  The sim is published, time to close.
