### ISSUE TITLE
add to active-runnables when development resumes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gene-expression-essentials#11]
Removed this sim from chipper/data/active-runnables until development resumes, so that we don't see issues with automated testing. Add it back in when development resumes.

**Comment by phet-steele** [comment]
Checked with @aadish to see if the sim was ready, he said check back in another week.

**Comment by phet-steele** [comment]
Added in https://github.com/phetsims/chipper/commit/69de18c3d8888c162f9f559d0d218352e661f45c
