### ISSUE TITLE
Grabbing a biomolecule during the gene switch animation will place it in the wrong gene

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gene-expression-essentials#112]
In quick succession, press "Next/Previous Gene" then grab a biomolecule from the toolbox. Doing this correctly requires that you grab the object before the animation has made any significant progress. The biomolecule will have been initialized on the gene you were traveling to, not on its "home" gene.

This traps biomolecules on the wrong gene ie. if you do this with a PTF, the gene it belonged to will not be able to transcribe since it will no longer have a PTF to use.

(a bit hard to see here, but just after I press the Next Gene button, I then press on the PTF for Gene 1, then I do it again with a ribosome)
![gee05](https://user-images.githubusercontent.com/5863899/33342923-df6c8e4a-d440-11e7-92b6-c20aeb7cc76d.gif)

Seen on iPad Air 2 iOS 10.3.3. For phetsims/QA/issues/68.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-rc.1/gene-expression-essentials_en.html
Version: 1.0.0-rc.1 2017-11-14 01:00:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Language: en-US
Window: 1920x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"80b60293","branch":"HEAD"},"babel":{"sha":"0421d844","branch":"master"},"brand":{"sha":"cfca902d","branch":"HEAD"},"chipper":{"sha":"6b338220","branch":"HEAD"},"dot":{"sha":"85ef2bbf","branch":"HEAD"},"gene-expression-essentials":{"sha":"a5872a07","branch":"HEAD"},"griddle":{"sha":"6f1477b5","branch":"HEAD"},"joist":{"sha":"ea429056","branch":"HEAD"},"kite":{"sha":"2c921cba","branch":"HEAD"},"phet-core":{"sha":"c30d15ed","branch":"HEAD"},"phetcommon":{"sha":"b13138d2","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"92a2872d","branch":"HEAD"},"scenery-phet":{"sha":"d394b9df","branch":"HEAD"},"sherpa":{"sha":"0d590744","branch":"HEAD"},"sun":{"sha":"99a0abef","branch":"HEAD"},"tandem":{"sha":"c1e98f69","branch":"HEAD"}}
</details>

**Comment by jbphet** [comment]
I fixed this by making the biomolecule tool boxes non-interactive (i.e. setting pickable to false) when animations are in progress.  I'll have it verified on the next RC.

**Comment by phet-steele** [comment]
Can no longer reproduce.
