### ISSUE TITLE
LoL Icons and Descriptions

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gene-expression-essentials#113]

**Comment by arouinfar** [comment]
Icons have been created and uploaded to Drive. @phet-steele it would be helpful to know a by-screen breakdown of the learning goals. Can you take a stab at that? Don't worry if they're not teacher-facing, I just need a rough idea.

**Comment by arouinfar** [comment]
@phet-steele I've drafted descriptions for GEE. Please let me know if these look reasonable. Feel free to comment in the issue, or edit the spreadsheet directly. (GEE can be found in the "Not_Ready" tab.)

**Expression:**
Express yourself through your genes! Experiment with the biomolecules in your toolbox to generate and collect three types of protein.

**mRNA:**
Take a deeper look at mRNA production. Control the concentrations and interactions of biomolecules, and determine how these factors affect the production of mRNA.

**Multiple Cells:**
Explore the factors that affect protein synthesis in a cell. Predict how changing the concentrations and interactions of biomolecules affects protein production, and discover how protein production in a single cell relates to the quantity produced by a collection of cells.

**Comment by arouinfar** [comment]
GEE was delivered to LoL after @phet-steele gave the descriptions his emoji of approval, but it looks like I forgot to close this issue.
