### ISSUE TITLE
Expression screen icon

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gene-expression-essentials#115]
This screen icon: https://github.com/phetsims/gene-expression-essentials/blob/master/images/manual-gene-expression-icon.png has a noticeably different background color behind the ribosome.

The ribosome/mRNA group also looks slightly low-res (the whole screen icon looks fine otherwise).

For phetsims/QA/issues/79.

**Comment by arouinfar** [comment]
Background color is at least fixed 🛩 🐌 🏂

**Comment by arouinfar** [comment]
For the record, @phet-steele hijacked my keyboard.

**Comment by phet-steele** [comment]
@jbphet I looked at the higher res one in https://github.com/phetsims/gene-expression-essentials/commit/4fb293302e46e90aa03e18396f09394705deae4a and it looked swell. I'll push it to 1.0 and close.

**Comment by phet-steele** [comment]
Thanks a million @arouinfar!
