### ISSUE TITLE
Items for Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gene-expression-essentials#116]
From Legacy Tips (likely to be reworded some)
- [x] The cell being modeled is prokaryotic cell, and so has no nucleus
- [x] On the “Multiple Cells” tab, the protein production being modeled is GFP (green
fluorescent protein)
- [x] On the “Cell Gene Expression” tab and on the “Messenger RNA Production” tab the
RNA polymerase and the transcription factors have a movement that is “pseudo random”
and tends to drive towards the Gene region.
- [x] One of the learning goals of the “Multiple Cells Tab” tries to lead students to see the
difference between the *average* protein level expressed by a single cell and multiple
cells. Students will likely need to pay attention to the level of fluctuations on the
dynamic protein level graph to make sense of this connection.
- [x] Students may not immediately see the goal of the “Messenger RNA Production” tab,
considering asking students to describe the factors that affect RNA production, or first
challenge them to produce RNA as quickly as possible.

From [model.md](https://github.com/phetsims/gene-expression-essentials/blob/master/doc/model.md) (also likely to be reworded some)
- [x] The process being portrayed does not show the mRNA moving out of the nucleus, and is thus essentially showing a prokaryotic, as opposed to a eukaryotic, cell.
- [x] The genes being transcribed are significantly shorter (in terms of the number of base pairs) than real-life genes. On average, a real gene in a prokaryotic organism is 1000 base pairs, whereas the genes in this simulation contain less than 100 base pairs.
- [x] Ribosomes are available to the user in "pre-assembled" form, meaning that the large and small subunits are already together, rather than having the subunits come together as mRNA transcription begins.
- [x] Individual amino acids are not depicted.
- [x] Transfer RNA (tRNA) is not depicted.
- [x] Protein folding is not depicted.
- [x] The sizes and shapes of the biomolecules were inspired by the drawing in "The Machinery of Life" by David S. Goodsell.

@phet-steele can you please review and let me know if there's anything else that needs to be documented in the Tips?

**Comment by phet-steele** [comment]
Seems swell to me 😄 , thanks!
