### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gene-expression-essentials#126]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Larger +/- boxes for accordion boxes may be useful.  See https://github.com/phetsims/sun/issues/500

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56244308-d8f80700-6059-11e9-9034-f2bf84a226d7.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56244309-d8f80700-6059-11e9-8cc4-27ebdbf9f5ed.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56244310-d8f80700-6059-11e9-8eb4-36023ad014c3.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/41024075/56244311-d8f80700-6059-11e9-93b8-5bb1c43fd8c2.png)
![Image from iOS (5)](https://user-images.githubusercontent.com/41024075/56244312-d8f80700-6059-11e9-99fb-d8b8db81f457.png)
![Image from iOS (6)](https://user-images.githubusercontent.com/41024075/56244313-d8f80700-6059-11e9-842b-8ceeeb787c8a.png)
![Image from iOS (7)](https://user-images.githubusercontent.com/41024075/56244314-d9909d80-6059-11e9-9d4d-113ca4486c24.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56244315-d9909d80-6059-11e9-91dc-be3648a9d581.png)

**Comment by arouinfar** [comment]
https://github.com/phetsims/sun/issues/500 would support asymmetric dilation of the `ExpandCollapseButton` but that isn't necessary here. 

@jbphet looks like there's plenty of room to dilate the touch areas a bit, as proposed in green.
![image](https://user-images.githubusercontent.com/8419308/56303953-38a5ef00-60fa-11e9-8fff-099c18dd9701.png)

**Comment by SaurabhTotey** [comment]
I have expanded the touch areas a little bit. I increased them from 5 to 8. Here is what it looks like in master.
<img width="1440" alt="geneexpressionsaccordionbox" src="https://user-images.githubusercontent.com/22577113/60211101-99008d80-981b-11e9-8b5a-7bcc674f8f1f.png">

**Comment by KatieWoe** [comment]
Looks good to me.  @arouinfar

**Comment by arouinfar** [comment]
👍
