### ISSUE TITLE
adjust touchArea options for HSlider thumb 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gene-expression-essentials#13]
In https://github.com/phetsims/sun/issues/254, the touchArea defaults for HSlider thumb were changed so that they default to pixels, not a percentage of the thumb size.  Sims that use HSlider's `thumbSize` option will therefore need to also specify `thumbTouchAreaXDilation` and `thumbTouchAreaYDilation`.

**Comment by pixelzoom** [comment]
Btw... There's some dead code in HorizontalSliderWithLabelsAtEnds that you might want to clean up.

**Comment by jbphet** [comment]
Assigning to @aadish, since he is taking over on this sim.

**Comment by aadish** [comment]
touch area looks good, closing
