### ISSUE TITLE
Use TimeControlNode for Play/Pause/Step buttons

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gene-expression-essentials#130]
From phetsims/scenery-phet#561. A scenery-phet/TimeControlNode was created that combines the PlayPauseButton and StepForwardButton and includes PhET-iO and PDOM instrumentation. It should be used in this sim. Assigning to responsible dev.

**Comment by SaurabhTotey** [comment]
I have replaced both instances of the PlayPauseButton and StepForwardButton pair with a TimeControlNode. Closing, but please reopen if there is anything left for this that I should do.
