### ISSUE TITLE
Higher average protein level after reset

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gene-expression-essentials#133]
Just noticed while working on #132. On sim load, the initial average protein level is starts at "none". After pressing reset all button the initial average protein level starts about 2/7 between 'None' and 'Lots'. Is this difference intentional? This does seem to be the behavior for the published sim.

**Comment by jbphet** [comment]
Good observation.  I guess no one ever noticed that before (our QA process with a bit less rigorous when this was originally published).  I've added code to step the model to a steady state equilibrium when created, and that makes it more consistent.  This doesn't seem worthy of a maintenance release, so I've only fixed it on master and it can go out the next time it is released from there.

Closing.
