### ISSUE TITLE
problems with ControlPanelNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gene-expression-essentials#134]
Same problem as in https://github.com/phetsims/area-builder/issues/114 ... 

ControlPanelNode is defining `this.expandedProperty`, which is also defined in the superclass.

ControlPanelNode is also poorly named.  It extends AccordionBox, so should have a name with "AccordionBox" suffix.

**Comment by pixelzoom** [comment]
In the above commit, I converted to ES6, deleted `this.expandedProperty`, and confirmed that Reset All is working.

I did not rename ControlPanelNode.

**Comment by jbphet** [comment]
I reviewed the commit and it looked good, and renamed `ControlPanelNode` to `ParameterControlAccordionBox`.  Closing.
