### ISSUE TITLE
Translatable Strings

### ISSUE THREAD

**Issue by aadish** [phetsims/gene-expression-essentials#17]
@ariel-phet  should any the strings in below image should be translatable or should we leave it as it is.
 
![image](https://cloud.githubusercontent.com/assets/4546788/19285591/d19ca616-8fb7-11e6-80ea-b789a1621933.png)

**Comment by ariel-phet** [comment]
@aadish the caption should be translatable - but not the copyright statement

**Comment by aadish** [comment]
string is translatable closing
