### ISSUE TITLE
Automated Testing Sim Error (10/25/2016 10:10 AM) 

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gene-expression-essentials#18]
`Uncaught Error: Script error for: GENE_EXPRESSION_ESSENTIALS/multiplecells/view/ControllerNode
`

@aadish, please change the file name for [controllerNode.js](https://github.com/phetsims/gene-expression-essentials/blob/e1ba700877d2acf7f85944c12957cdc22a8e828b/js/multiplecells/view/controllerNode.js) to have a capital "C".

**Comment by aadish** [comment]
fixed, closing
