### ISSUE TITLE
mRNA is manipulatable by its label

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gene-expression-essentials#22]
The labels on mRNA ("mRNA") are pickable, allowing you to move them around. This is true whether or not they are visible (they can be manipulated when they are floating around, minding their own business). Occurs on both the first two screens:

![gee01](https://cloud.githubusercontent.com/assets/5863899/22610603/7398fa1c-ea23-11e6-8ce4-d0f96c0bb602.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#776.

URL: http://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.2/gene-expression-essentials_en.html
Version: 1.0.0-dev.2 2017-01-30 19:21:44 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36
Language: en-US
Window: 1920x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"1cf10281","branch":"master"},"babel":{"sha":"10f77fec","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"f4cd39bf","branch":"master"},"dot":{"sha":"75380061","branch":"master"},"gene-expression-essentials":{"sha":"9e5baa27","branch":"master"},"joist":{"sha":"d15e6fab","branch":"master"},"kite":{"sha":"6059ebb0","branch":"master"},"phet-core":{"sha":"84747dff","branch":"master"},"phetcommon":{"sha":"1cb33196","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"550df01a","branch":"master"},"scenery-phet":{"sha":"b04d8086","branch":"master"},"sherpa":{"sha":"785a536c","branch":"master"},"sun":{"sha":"d0708aa5","branch":"master"},"tandem":{"sha":"d9c124e5","branch":"master"}}

**Comment by brroberts1231** [comment]
It appears to me that they are _only_ manipulatable by the text, and not by the body of it. Clicking on the black squiggle seems to do nothing, and you have to find the invisible box of text in order to move them around, which can especially be a problem if they float to the top of the screen and only the bottom of the mRNA shows.

**Comment by phet-steele** [comment]
Looks great, thanks @aadish.
