### ISSUE TITLE
Destroyer grab issue

### ISSUE THREAD

**Issue by BryceAG** [phetsims/gene-expression-essentials#24]
It is possible (although difficult) to get the ribosome to grab onto the mRNA while the polymerase is creating it. However, if this is attempted with a destroyer, the destroyer will slip off, and become ungrabable until it reconnects and eats the mRNA. Furthermore, the specific destroyer and mRNA are linked, and other destroyers cannot eat that mRNA.

![pacman no eat eat](https://cloud.githubusercontent.com/assets/15327201/22666264/1abc9f8a-ec75-11e6-8d73-9778ca218209.gif)

related to phetsims/tasks#776

URL: http://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.2/gene-expression-essentials_en.html
Version: 1.0.0-dev.2 2017-01-30 19:21:44 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36
Language: en-US
Window: 1366x662
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"1cf10281","branch":"master"},"babel":{"sha":"10f77fec","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"f4cd39bf","branch":"master"},"dot":{"sha":"75380061","branch":"master"},"gene-expression-essentials":{"sha":"9e5baa27","branch":"master"},"joist":{"sha":"d15e6fab","branch":"master"},"kite":{"sha":"6059ebb0","branch":"master"},"phet-core":{"sha":"84747dff","branch":"master"},"phetcommon":{"sha":"1cb33196","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"550df01a","branch":"master"},"scenery-phet":{"sha":"b04d8086","branch":"master"},"sherpa":{"sha":"785a536c","branch":"master"},"sun":{"sha":"d0708aa5","branch":"master"},"tandem":{"sha":"d9c124e5","branch":"master"}}

**Comment by BryceAG** [comment]
Just to clarify, it is possible for the destroyer to eat while the mRNA is being created (done successfully by dragging the mRNA into the destroyer), but if not done correctly then the above error happens.

**Comment by aadish** [comment]
@phet-steele this behavior is similar to the one in Java Simulation, is this a bug or desired behavior?

**Comment by phet-steele** [comment]
@aadish this is broken behaviour that should be fixed. It is not hard to end up in the situation (in the above video) where the sim feels very broken, ie. you can't control a particular destroyer and you can't attach the other destroyer to the mRNA. Ideally, the destroyer heading to an mRNA should be able to be "cancelled" by user interaction with the same destroyer, the mNRA in question, or by attaching a different destroyer to the mRNA in question.

**Comment by jbphet** [comment]
I've verified that this no longer occurs on master, will leave open and unassigned for verification in next dev or RC release.

**Comment by jbphet** [comment]
The original solution to this was to have the destroyers and ribosomes jump to the mRNA instead of move there in some sort of animation.  This looked odd, see #91, so the behavior has been modified as described in https://github.com/phetsims/gene-expression-essentials/issues/91#issuecomment-339088501.  We should still verify that this is fixed, but will need to keep the new expected behavior in mind.

**Comment by phet-steele** [comment]
The very quick animation is much better than the jump! Fixed, but if this solution isn't sufficient and is causing #94, we can track that there.
