### ISSUE TITLE
Objects often float off screen at top

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/gene-expression-essentials#25]
It happens pretty frequently that objects will float to the top of the screen and be difficult or impossible to click and drag back onto screen. 
In the screenshot below, the RNA Destroyer on the left was floating around just at the edge of the screen, and was very difficult to grab, and there was also a second protein floating completely above the edge at the same time which could not be seen at all. 

![screen shot 2017-02-06 at 2 18 31 pm](https://cloud.githubusercontent.com/assets/11947677/22666764/343b0f58-ec77-11e6-9995-efd928534060.png)
Related to phetsims/tasks#776 
Seen on macOS 10.12 chrome.

Troubleshooting information (do not edit):
Name: ‪Gene Expression Essentials‬
URL: http://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.2/gene-expression-essentials_en.html
Version: 1.0.0-dev.2 2017-01-30 19:21:44 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36
Language: en-US
Window: 1147x612
Pixel Ratio: 1/1
WebGL: disabled (Web page was not allowed to create a WebGL context. Web page was not allowed to create a WebGL context. )
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"1cf10281","branch":"master"},"babel":{"sha":"10f77fec","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"f4cd39bf","branch":"master"},"dot":{"sha":"75380061","branch":"master"},"gene-expression-essentials":{"sha":"9e5baa27","branch":"master"},"joist":{"sha":"d15e6fab","branch":"master"},"kite":{"sha":"6059ebb0","branch":"master"},"phet-core":{"sha":"84747dff","branch":"master"},"phetcommon":{"sha":"1cb33196","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"550df01a","branch":"master"},"scenery-phet":{"sha":"b04d8086","branch":"master"},"sherpa":{"sha":"785a536c","branch":"master"},"sun":{"sha":"d0708aa5","branch":"master"},"tandem":{"sha":"d9c124e5","branch":"master"}}

**Comment by phet-steele** [comment]
@aadish the new restrictions haven't caused any problems for me, thanks.
