### ISSUE TITLE
need design and/or artwork for home screen and nav bar icons

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#27]
As of this writing, the home screen and nav bar icons are blank.  I'm not sure who should come up with the icons for these - I could probably do it if necessary - but I thought I'd log an issue and have @ariel-phet decide who should take care of it.

**Comment by aadish** [comment]
@jbphet @ariel-phet had forwarded me the initial screenshots which can be used as icons, I will put them up and then decide further on improving them

**Comment by aadish** [comment]
this the initial thoughts by @ariel-phet. Putting here for reference

> As for icons...I think you can for the moment just use items from the screens already drawn in code. Lets change the screen names to the following for the moment, with the attached sketch of icons (JB let me know if you feel differently). The icons are basically just screenshots of things in the sim

**Comment by aadish** [comment]
@ariel-phet , @jbphet , @phet-steele I have put the initial icons for this sim which are the screenshot of individual components on the screens

Let me know your thoughts and we can take it from there

**Comment by ariel-phet** [comment]
@aadish looking pretty good. One main change - please remove all text from the icons (we don't usually put text in the icons since translation would be trick, and it will be too small to read on the nav-bar)

**Comment by aadish** [comment]
removed text

**Comment by phet-steele** [comment]
@aadish without the text on the first screen image, the image is pretty bland. I'm not saying text is a good thing, because it isn't, but I feel we need something more on this screen image. I was thinking something more along the line of:

<img width="410" alt="screen shot 2017-03-22 at 10 42 14 am" src="https://cloud.githubusercontent.com/assets/5863899/24209849/04897d92-0eed-11e7-9a99-1b3c0dc76ae4.png">

Or without the DNA (and centered better):
<img width="301" alt="screen shot 2017-03-22 at 10 41 26 am" src="https://cloud.githubusercontent.com/assets/5863899/24209869/0e3e9af2-0eed-11e7-958f-fad638aa5f97.png">

@ariel-phet @aadish, thoughts?

**Comment by phet-steele** [comment]
@aadish Also, the image for the Multiple Cells screen is *very* hard to see. We may need the cells in that image to be much more green.

Here's how they look now:
<img width="1456" alt="screen shot 2017-03-22 at 10 51 24 am" src="https://cloud.githubusercontent.com/assets/5863899/24210112/ba00fef2-0eed-11e7-8d4f-4ebab76f3882.png">

Navbar:
<img width="659" alt="screen shot 2017-03-22 at 10 51 29 am" src="https://cloud.githubusercontent.com/assets/5863899/24210115/be0c0adc-0eed-11e7-89eb-cc797a67eefa.png">

**Comment by ariel-phet** [comment]
@phet-steele you are sort of "lead designer" on this sim these days, and I trust your opinion. Agreed on the multiple cells, and would agree with potentially adding detail to the first icon.

**Comment by jbphet** [comment]
I like the version that shows the ribosome and the DNA strand.  I also agree that the cells should be much more green for 3rd icon.

**Comment by aadish** [comment]
@phet-steele let me know how the icons look

**Comment by phet-steele** [comment]
Discussed with @aadish, the new screenshots look great and the green really helps. The 3rd screen image does seem to be a little "low". There is some empty black space along the top and the cells along the bottom are cropped. An image that is "higher" will look great here.

**Comment by phet-steele** [comment]
Current one looks great!
