### ISSUE TITLE
collection area gets too wide with long strings

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#29]
I just did the long string test on the current master version and noticed that the collection area gets unreasonably wide.  Screenshots below.

Double string test:
![gee-wide-capture](https://cloud.githubusercontent.com/assets/3082831/22999411/66f2a01e-f398-11e6-9941-79f6de0eff99.PNG)

Normal size:
![gee-normal-capture](https://cloud.githubusercontent.com/assets/3082831/22999415/6f5b16fa-f398-11e6-808a-1bafa711edfa.PNG)

The problem is even more pronounced when using `stringTest=long`

**Comment by aadish** [comment]
fixed closing
