### ISSUE TITLE
fill in the credits

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#31]
Please go ahead an add the initial set of credits, using those from the original Java simulation, adding @aadish as a developer, and adding @phet-steele for QA.  Once this is done, please unassign the issue and leave it open with a note that the credits still need to be finalized before publication.

Also, add in anyone who has worked as a designer on this version (if anyone has).

**Comment by jbphet** [comment]
Oh, and please also add @AshrafSharf as one of the developers.

**Comment by jbphet** [comment]
The credits currently have @phet-steele as the lead designer.  This doesn't seem quite right, since he was only assigned that role recently.  The Java version doesn't have a lead designer, and lists a number of people as designers.  I propose omitting the "Lead Design" credit for this sim and adding @phet-steele to the 'Team' credits.  Sound reasonable?

**Comment by jbphet** [comment]
@phet-steele - please let me know who should be added to the QA credits when you know everyone who will - or did - work on the test effort.

**Comment by phet-steele** [comment]
Credits should be correct!
