### ISSUE TITLE
multi-line comments should wrap at the 120th column

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#32]
The current PhET coding convention is that comments wrap at 120 columns, not at 80, as I'm seeing as I start reviewing the code.  120 was agreed upon because most modern screens accommodate it and it allows us to get more code on the screen.  For example, this comment in `ManualGeneExpressionModel.js`

```
    // List of areas where biomolecules should not be allowed.  These are
    // generally populated by the view in order to keep biomolecules from
    // wandering over the tool boxes and such.
```
should instead be
```
    // List of areas where biomolecules should not be allowed.  These are generally populated by the view in order to 
    // keep biomolecules from wandering over the tool boxes and such.
```
...which takes up fewer lines.

Please go through the code and format all multi-line comments to match this convention.

**Comment by aadish** [comment]
fixed closing
