### ISSUE TITLE
not loading on ipad2

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#36]
While working through the code review checklist (see #3), I decided to try loading on an iPad 2.  The current master version doesn't load successfully.  It starts, and the loading screen and progress bar are shown, and the bar moves, but before it gets all the way across the browser puts up an error message and tries reloading.

I've seen this on both the requireJS and the compiled versions.

iOS version 9.3.5

**Comment by aadish** [comment]
master currently loads on iPad, but performace is not upto the benchmark
this issue is similar to #50, closing it and tracking there
