### ISSUE TITLE
replace usages of _.forEach

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#42]
I'm seeing a number of usages of `_.forEach` instead of the native JS `forEach` function.  We should use the latter if we can.  If there is a good reason to use the lodash version, feel free to enlighten me.  A search of the code shows 21 usages for this sim.

Example from ManualGeneExpressionModel:

```js
      _.forEach( this.offLimitsMotionSpaces, function( offLimitMotionSpace ) {
        if ( bounds.intersectsBounds( offLimitMotionSpace ) ) {
          // bounds.subtract( new Area( offLimitMotionSpace ) ); TODO
        }
      } );
```

**Comment by aadish** [comment]
fixed closing
