### ISSUE TITLE
We should have proper formatting for bacterial nomenclature

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gene-expression-essentials#44]
@aadish we should do one of two things for the "Real Cells" image caption. In either case, we should italicize *E. coli* AND make "*coli*" lowercase. I see the options we have being:

1). Italicize, lower case and stop there, results in: *E. coli*.
2). Italicize, lower case, and do not use the abbreviation, results in: *Escherichia coli*.

I believe option 2 is more proper since it's the first and only time in the sim we refer to the bacteria by name. However, I'm okay with option 1 if we do not have room for such a long string. @aadish, can you try to fit in option 2 first and we go from there?

For phetsims/tasks/issues/776.

**Comment by aadish** [comment]
@phet-steele I pushed changes to reflect option 2 take a look at master and let me know how does it look and any other changes required

**Comment by phet-steele** [comment]
@aadish Hooray we have room! Thanks! Two things to note:

- We lost the period at the end of the first sentence, after (GFP).
- Can we get rid of the space between the first and second lines? (Highlighted with the red box)

<img width="924" alt="screen shot 2017-03-22 at 10 55 52 am" src="https://cloud.githubusercontent.com/assets/5863899/24210366/7718d3ac-0eee-11e7-8cf8-7eb7d7226336.png">

**Comment by aadish** [comment]
@phet-steele pushed changes let me know how it looks now

**Comment by phet-steele** [comment]
Discussed with @aadish, the new screenshots look great and the green really helps. The 3rd screen image does seem to be a little "low". There is some empty black space along the top and the cells along the bottom are cropped. An image that is "higher" will look great here.

**Comment by phet-steele** [comment]
The latest still has a slight gap between the first and second lines. This may be a result of different font sizes being used in each line. @aadish is investigating. Here is the latest:
<img width="927" alt="screen shot 2017-04-10 at 11 01 02 am" src="https://cloud.githubusercontent.com/assets/5863899/24873177/2dab60ec-1ddd-11e7-987d-d591c3fecf0a.png">

**Comment by aadish** [comment]
@phet-steele let me know how it looks just pushed the changes

**Comment by phet-steele** [comment]
Looks great!
