### ISSUE TITLE
names look incorrect for several methods that were overloaded in Java version

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#46]
In the class `DnaMolecule` in the Java version of this sim, there were several overloaded methods used to request that the DNA molecule consider a proposal for a given biomolecule to attach.  These were renamed to specific methods in the JavaScript version since JavaScript doesn't support this kind of overloading, but the naming seems odd.  For instance, in the Java version, there is a method:
 ```Java
public AttachmentSite considerProposalFrom( final TranscriptionFactor transcriptionFactor )
```

In the JavaScript port, the equivalent method is called
```js
considerProposalFromByTranscriptionFactor
```

It's the "FromBy" part that seems odd to me.  If there isn't a good reason why this is present, all methods with similar names should replace the "FromBy" part with "From".

**Comment by aadish** [comment]
fixed, closing
