### ISSUE TITLE
commented out assertion in DnaMolecule should be fixed or removed

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#48]
The file `DnaMolecule.js` contains the line:
```js
      // assert xOffset >= leftEdgeXOffset && xOffset < leftEdgeXOffset + moleculeLength;
```
This seems like a reasonable check, and I'm wondering why it is commented out.  It should be added back, fixing it if possible, or removed if there is a good reason to do so.

**Comment by aadish** [comment]
fixed closing
