### ISSUE TITLE
can static declarations of CONFORMATIONAL_CHANGE_RATE be removed

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#49]
There are two files that use a constant called CONFORMATIONAL_CHANGE_RATE, both declare it as a static constant, and as far as I can tell, no one uses these static declarations.  So, two questions:

+ Should this be a single constant shared between the two files, and thus maintained in the shared constants file?
+ Can the static public declarations be removed?

**Comment by aadish** [comment]
fixed closing
