### ISSUE TITLE
memory usage is extremely high

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#50]
I just did a heap snapshot where I started up the sim, then opened the first screen, the took the snapshot.  Total memory usages is a whopping 249 MB.  I ran the same test on States of Matter, and the total was 23.1 MB, so GEE is using over 10x as much memory.  That's way too much, and it needs to be investigated and reduced.

This may well explain why the sim isn't running on iPads (see #36).

**Comment by aadish** [comment]
Snapshot of the sim after running Fuzz Mouse for 30 minutes memory usage is 48 MB, which is a significant drop

**Comment by jbphet** [comment]
I just re-ran the test described in the initial comment on Chrome 59.0.3071.115 in an incognito window on Win 10.  The memory usage was reported at 40.0 MB.  I'd say that the initial problem has been addressed, and I will track other memory profiling in another GitHub issue.  Closing.
