### ISSUE TITLE
Multiple cells screen: reset all button doesn't restart play

### ISSUE THREAD

**Issue by BryceAG** [phetsims/gene-expression-essentials#53]
If the sim is paused on the multiple cells screen, then the reset all button is pressed, the sim will revert all values to default and clear the graph as it should, but the sim will remain paused and play will have to be pressed again.

related to phetsims/tasks#776.

Name: ‪Gene Expression Essentials‬
URL: http://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.2/gene-expression-essentials_en.html
Version: 1.0.0-dev.2 2017-01-30 19:21:44 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Language: en-US
Window: 1366x662
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"1cf10281","branch":"master"},"babel":{"sha":"10f77fec","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"f4cd39bf","branch":"master"},"dot":{"sha":"75380061","branch":"master"},"gene-expression-essentials":{"sha":"9e5baa27","branch":"master"},"joist":{"sha":"d15e6fab","branch":"master"},"kite":{"sha":"6059ebb0","branch":"master"},"phet-core":{"sha":"84747dff","branch":"master"},"phetcommon":{"sha":"1cb33196","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"550df01a","branch":"master"},"scenery-phet":{"sha":"b04d8086","branch":"master"},"sherpa":{"sha":"785a536c","branch":"master"},"sun":{"sha":"d0708aa5","branch":"master"},"tandem":{"sha":"d9c124e5","branch":"master"}}

**Comment by phet-steele** [comment]
Fixed, thanks @BryceAG and @aadish.
