### ISSUE TITLE
Sim won't load in IE, math.log10 not supported

### ISSUE THREAD

**Issue by BryceAG** [phetsims/gene-expression-essentials#54]
The load bar gets about 80% full then stops when trying to open on Internet Explorer. Looking into the console shows math.log10 is not supported.

related to phetsims/tasks#776.

Sim would not load so not all trouble shooting information could be gathered
Name: ‪Gene Expression Essentials‬
URL: http://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.2/gene-expression-essentials_en.html
Version: 1.0.0-dev.2 2017-01-30 19:21:44 UTC
Features missing: touch

**Comment by jbphet** [comment]
The commit from @aadish above removes that usage of `math.log10`, and I just inspected the code to make sure it doesn't appear.  I also tested on IE and it loaded fine with no errors.  Closing.
