### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#55]
@aadish and I are currently working to bring the memory usage down to an acceptable level (see #50), and by using a canvas for the DNA strand the memory usage has fallen substantially.  This appears to have enabled the simulation to operate on iPad 2 devices (see #36).  The performance on iPad 2 is pretty low, sitting at around 10 fps before anything is happening (probably due to the DNA strand being redrawn every frame) and dropping to 6 fps when basic transcription is in progress.  @aadish, @jonathanolson, and I just spoke for a while to come up with an initial plan for working on optimizations, and here is what we are thinking:

1. Change the canvas node `paintCanvas` such that it only redraws when needed, i.e. when deformation of the DNA has occurred due to transcription.
2. Publish a fully working dev version that can be used to qualify the performance and can act as a baseline against which to measure progress.
3. Change the `paintCanvas` method to do as few draw calls as it can by drawing the back portions of the two backbones, then all of the base pairs, then the front portions of the backbone, for a total of 5 draw calls.
4. Change the `paintCanvas` method to have awareness of the viewport and to not draw outside of it.
5. Set the transform of the canvas node to be the model few transform so that each point of the DNA strand doesn't have to be transformed.  We will have to calculate stroke widths for this.

**Comment by jbphet** [comment]
One of the performance issues is the rendering of the mRNA.  This is closely related to issue #65.  I've implemented a simpler algorithm for defining the mRNA shape, and then did some profiling, and found that the animation frames are still taking a fairly long time when creating the mRNA.  After some discussion with @jonathanolson, I learned that changing shapes for a complex shape is fairly expensive in Scenery when using accurate bounds computation.  Since the code knows what the bounds of the mRNA should be, I decided to try setting the bounds method for the mRNA node (`MessengerRnaNode`) to 'none' and setting them explicitly when the model shape changes.  This did seem to provide benefits, so I'm going to gather the data here in order to track how much improvement occurs.

My test procedure for this is to profile in Chrome while creating mRNA on the Manual Gene Expression screen, first gene.  I'll record the length of the 10 animation frames when the polymerase is right in the middle of the gene.  I'll do this on RequireJS versions before and after the change where the bounds are explicitly set.  Chrome now allows us to see exactly what the sim looked like at each moment during the profile, and below is what my screen looked like when examining the recorded profile.  Note that the polymerase is positioned right in the middle of the gene as determined the the "Transcribed Region" label.

![gee-profile](https://user-images.githubusercontent.com/3082831/29379173-c7fc87ce-827e-11e7-99ca-c7f76c7d284b.png)

Before change:

| Trial | Animation Frame Length (ms) |
| ------------- | ------------- |
| 1 | 38.50 |
| 2 | 29.71 |
| 3 | 38.04 |
| 4 | 33.37 |
| 5 | 47.63 |
| 6 | 33.72 |
| 7 | 37.53 |
| 8 | 30.67 |
| 9 | 40.98 |
| 10 | 43.49 |
| **avg** | 37.36 |

After the change:

| Trial | Animation Frame Length (ms) |
| ------------- | ------------- |
| 1 | 6.51 |
| 2 | 7.91 |
| 3 | 9.19 |
| 4 | 5.58 |
| 5 | 9.19 |
| 6 | 6.09 |
| 7 | 10.26 |
| 8 | 7.13 |
| 9 | 10.84 |
| 10 | 5.08 |
| **avg** | 7.78 |

So, on average, it looks like this change improved the animation frame time by a factor of 37.36 / 7.78 = 4.8x.  That's pretty decent - I'll go ahead and commit it.

**Comment by jbphet** [comment]
Oh, I should record the parameters for the algorithm that generates the mRNA shape so that this can be repeated precisely if needed.  They are:

```js
WINDING_PARAMS = {
    "yWave1Frequency": 0.03350868765331309,
    "yWave1PhaseOffset": 1.4652859313212294,
    "yWave1Multiplier": 0.3523018499297727,
    "yWave2Frequency": 0.03679270540637452,
    "yWave2PhaseOffset": 0.8290895969945882,
    "yWave2Multiplier": 0.3710465106439804,
    "xWaveFrequency": 0.06762818354262706,
    "xWavePhaseOffset": 1.3697784268233215,
    "xWaveMultiplier": 0.19589544619869786
}
```

**Comment by jbphet** [comment]
Another potential improvement would be to have the messenger RNA model element `MessengerRna` report its bounds as those of the shape segment so that the more complicated calculation of the bounds for the actual twisty mRNA shape could be avoided.

**Comment by jbphet** [comment]
Suggestion: Using pooling for Vector2 and Bounds.

**Comment by jbphet** [comment]
I showed @ariel-phet version 1.0.0-dev.12 (https://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.12/), and he said that he thought the performance was "acceptable".  We decided to spend a little bit more time looking for easy optimizations to make, but not to investigate more complicated options like rendering all the biomolecules on a canvas.

With this in mind, I'm going to qualify the performance of v1.0.0-dev.12 on my Win10 machine using Chrome and on an iPad 2 in Mobile Safari, then implement some potential improvements and see if there is a measurable gain.

**Comment by jbphet** [comment]
Below is a set of test cases that I suspect will be useful in identifying performance problems on the iPad.  These are all done on the "Expression" screen (screen 1), gene 1.  These indicies will be used to identify the tests used in subsequent entries in this issue.

1. RNA polymerase transcribing mRNA, only a single RNA polymerase and the positive transcription factor out of the tool box
2. ribosome transcribing mRNA, RNA polymerase floating around, transcription factor on DNA strand
3. mRNA destroyer destroying mRNA strand, RNA polymerase and ribosome floating around, transcription factor on DNA strand
4. two polymerase, two ribosomes, and two mRNA destroyers floating around, no other biomolecules out of the tool box
5. moving back and forth between the genes while a polymerase has been pulled out of the toolbox and is floating around for each

**Comment by jbphet** [comment]
Testing on Chrome, Win 10, my Dell XPS, on the main display with window at full size, new incognito window.  URL = https://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.12/gene-expression-essentials_en.html?profiler.  For each test I'm going to capture the following:

+ full screenshot of when the data was captured for the first test
+ enhanced screenshot portion with just the profile info, made more readable
+ results of 2nd trial with visibility enhanced
+ results of 3rd trial with visibility enhanced

Test 1 - mRNA Transcription
------------------------------

Screen capture take immediately after the first update after the transcription finished.

![image](https://user-images.githubusercontent.com/3082831/31635102-eaed52de-b282-11e7-8d24-c9fb054df09e.png)

![image](https://user-images.githubusercontent.com/3082831/31634847-0ce5cfb6-b282-11e7-8590-c85deca7e74a.png)
![image](https://user-images.githubusercontent.com/3082831/31635757-31ce86ee-b285-11e7-810a-24dc47b5db1b.png)
![image](https://user-images.githubusercontent.com/3082831/31635934-dd8491ea-b285-11e7-9e6e-3e6ebb938390.png)

Test 2 - mRNA Translation
----------------------------

![image](https://user-images.githubusercontent.com/3082831/31636337-435becb0-b287-11e7-808e-3ae15c929979.png)
![image](https://user-images.githubusercontent.com/3082831/31636165-a0684ce2-b286-11e7-90e3-fbd3818a8970.png)
![image](https://user-images.githubusercontent.com/3082831/31636224-d546d62c-b286-11e7-80e8-7f3832f4be42.png)
![image](https://user-images.githubusercontent.com/3082831/31636295-0d2cfbc0-b287-11e7-9c49-bea357957207.png)

Test 3 - Floating Biomolecules
---------------------------------

![image](https://user-images.githubusercontent.com/3082831/31636546-21470820-b288-11e7-9a22-88f4232dea13.png)
![image](https://user-images.githubusercontent.com/3082831/31636585-4d9846d2-b288-11e7-9c6c-aa017b2017de.png)
![image](https://user-images.githubusercontent.com/3082831/31636625-7e7fce28-b288-11e7-92e4-0c414eacdaef.png)
![image](https://user-images.githubusercontent.com/3082831/31636672-ba08fdc0-b288-11e7-8e6f-2f347c07d863.png)

Test 4 - Switching Between Genes
-------------------------------------

![image](https://user-images.githubusercontent.com/3082831/31637371-a1876036-b28b-11e7-9d1f-39c7864f48db.png)
![image](https://user-images.githubusercontent.com/3082831/31637901-1c210f52-b28e-11e7-95e6-b7fcb2531bd0.png)
![image](https://user-images.githubusercontent.com/3082831/31637990-86aac188-b28e-11e7-847b-7e0a62282656.png)
![image](https://user-images.githubusercontent.com/3082831/31638053-c5b2cc2c-b28e-11e7-9a6a-2794042f4e1f.png)

**Comment by jbphet** [comment]
Same tests and data from iPad 2 (Tycho), iOS 9.3.5:

Test 1 - mRNA Transcription
------------------------------

![ipad-01](https://user-images.githubusercontent.com/3082831/31639360-94bfb3da-b295-11e7-9b2c-7dbb90c9dc9d.png)
![ipad-01-profile](https://user-images.githubusercontent.com/3082831/31639361-9b8b0f2a-b295-11e7-9dc5-ac0a1f1e22d8.png)
![ipad-02](https://user-images.githubusercontent.com/3082831/31639365-9f0dec6c-b295-11e7-839e-8d4143d38c39.png)
![ipad-03](https://user-images.githubusercontent.com/3082831/31639367-a54425ec-b295-11e7-9630-6df52e3eeaa0.png)

Test 2 - mRNA Translation
----------------------------

![ipad-04](https://user-images.githubusercontent.com/3082831/31639372-ab4380be-b295-11e7-9316-48405a568b8e.png)
![ipad-04- profile](https://user-images.githubusercontent.com/3082831/31639374-b152b25e-b295-11e7-85d7-a3648b0d07b8.png)
![ipad-05](https://user-images.githubusercontent.com/3082831/31639379-b4caabee-b295-11e7-9fdf-f20216b0171c.png)
![ipad-06](https://user-images.githubusercontent.com/3082831/31639381-b88a4b72-b295-11e7-85fd-b96601aaf30c.png)

Test 3 - Floating Biomolecules
---------------------------------

![ipad-07](https://user-images.githubusercontent.com/3082831/31639383-bf76023c-b295-11e7-9620-d35480ecfdb0.png)
![ipad-07-profile](https://user-images.githubusercontent.com/3082831/31639385-bf8c8836-b295-11e7-918a-06a679f85973.png)
![ipad-08](https://user-images.githubusercontent.com/3082831/31639386-bf9f6942-b295-11e7-9344-7d61dc8b5bf4.png)
![ipad-09](https://user-images.githubusercontent.com/3082831/31639387-bfb6d172-b295-11e7-95c9-8fd2cd232826.png)

Test 4 - Switching Between Genes
-------------------------------------

![ipad-10](https://user-images.githubusercontent.com/3082831/31639396-c69f4014-b295-11e7-88e1-f165466a9acd.png)
![ipad-10-profile](https://user-images.githubusercontent.com/3082831/31639397-c6b500ca-b295-11e7-8ae9-31cb300555ec.png)
![ipad-11](https://user-images.githubusercontent.com/3082831/31639398-c6c65f96-b295-11e7-9532-30b2490f9e27.png)
![ipad-12](https://user-images.githubusercontent.com/3082831/31639399-c6e0e460-b295-11e7-819a-6701b1b26da9.png)

**Comment by jbphet** [comment]
The worst case is when mRNA is being transcribed by the mRNA polymerase, and switching between the genes is a close second.  I'll focus on improving these first.

**Comment by phet-steele** [comment]
While testing 1.0.0-dev.13, @BryceAG said:

All sections of the sim can easily be brought to having 5 FPS. For Expression just creating RNA with polymerase will drop the frame rate down to 10 FPS, and if you pull out a couple of the Biomolecules for each gene it will drop to 5. With mRNA just raising the concentration of the Positive Transcription Factor to High will drop the frame rate to ~6-8, and adding some negative Transcription Factor will drop it to 5. and for Multiple Cells, without changing anything else, just going to "many" cells will drop the frame rate to 5.

I know that poor performance is probably expected with iPad 2, but it is fairly easy to get this low of a frame rate. Related to phetsims/QA#58

**Comment by jbphet** [comment]
I've made a number of changes intended to improve performance and, though the frame rate on an iPad 2 is still not great (see the comment immediately above), I thought it would be worthwhile to repeat the measurements made above on a version built from master.  The results are below.  I didn't take the time to do screenshots this time around - I just did the tests and recorded the frame rates.

Dell XPS (@jbphet's machine), Chrome Version 61.0.3163.100 (Official Build) (64-bit), full screen on main display
===================================================================

Test 1 - mRNA Transcription
------------------------------

FPS = 32, 32, 33
Avg FPS = 32.33
Change = ( 32.33 - 26 ) / 26 = 24% improvement

Test 2 - mRNA Translation
----------------------------

FPS = 60, 60, 60
Avg FPS = 60
Change = ( 57 - 60 ) / 57 = 5% improvement


Test 3 - Floating Biomolecules
---------------------------------

FPS = 60, 59, 53
Avg FPS = 57.33
Change = ( 57.33 - 54.67 ) / 54.67 = 5% improvement

Test 4 - Switching Between Genes
-------------------------------------

FPS = 46, 43, 49
Avg FPS = 57.33
Change = ( 57.33 - 32 ) / 32 = 5% improvement

**Comment by jbphet** [comment]
I have to be honest and say that I'm not super confident that this testing constitutes a rigorous experiment with repeatable results, since I think there could be a number of variables that affect performance that are not being fully accounted for.  For instance, does it make a difference how recently the iPad was rebooted? Could there be fewer background processes running during one test than another?  Were enough trials run to assure statistically significant results?  Having said that, I find it encouraging that there appear to have been improvements of some amount for every test on both platforms.  I'm going to unassign this issue for now and will have @ariel-phet make an on-the-record determination of whether the performance is good enough once the RC is published.

**Comment by jbphet** [comment]
@ariel-phet - the first RC has been published, see https://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-rc.1/gene-expression-essentials_en.html.  Please evaluate on an iPad 2 and update this issue, either closing it or prioritizing it for further effort.

**Comment by ariel-phet** [comment]
@jbphet performance looks acceptable to me. In this particular sim we benefit from the fact that some choppiness can be interpreted as Brownian motion. But overall, I think on iPad 2 things look fine and where performance is a bit slow, there are no pedagogical implications. 

Closing

**Comment by BryceAG** [comment]
Reopening because of Edge performance. Following the above test format, the FPS is often worse than on iPad 2, despite chrome performing much better using the same hardwared laptop. The simplified results are:

Test 1 - mRNA Transcription

Avg FPS ~ 12

Test 2 - mRNA Translation

Avg FPS ~ 13

Test 3 - Floating Biomolecules

Avg FPS ~ 9.5

Test 4 - Switching Between Genes

Avg FPS ~ 15

Also for section 2 "mRNA" of the sim, increasing the positive transcription factors concentration to "high" results in an FPS ~8, and also adding negative transcription factors to "high" results in ~6 FPS.

assigning @ariel-phet to determine if performance is still acceptable

**Comment by ariel-phet** [comment]
@BryceAG thanks for pointing out edge issues.

I tested on Edge, and although the sim is "choppy" given the context of this sim , the performance is still acceptable.
