### ISSUE TITLE
RNA Polymerase can be manipulated on the second screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gene-expression-essentials#56]
@aadish, on current master (3/22, noon), the RNAP on the second screen can be dragged if it satisfies two conditions:
- the RNAP has participated in transcription
- the RNAP is to the left of the transcription start site.

Once it is dragged the first time, it can always be dragged. You may need to let some transcription occur to have RNAP appear on the left.

![gee03](https://cloud.githubusercontent.com/assets/5863899/24213027/ca3ea522-0ef6-11e7-8b70-86bb82f0d835.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks/issues/776.

**Comment by phet-steele** [comment]
@aadish there is still a brief moment (following the steps above) where RNAP can be grabbed just before it begins transcription. I showed @aadish in person since recording this on a video is tricky.

**Comment by jbphet** [comment]
Assigning to myself since I'm taking over this sim.

**Comment by jbphet** [comment]
I'm unable to duplicate, and the commit that @aadish made seems like it would fix the issue.  Back to @phet-steele to test on master and make sure that he can't duplicate it either.

**Comment by phet-steele** [comment]
Can't repro after that second commit.
