### ISSUE TITLE
comments should be added for the former inner class states

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#58]
There are a number of types that were inner classes in the Java version of the sim that have been pulled out into their own type in the JavaScript version, such ass `AttachedAndConformingState.js`.  This is fine, but in the context of the Java simulation, it was clear that `AttachedAndConformingState` only related to RNA polymerase.  This isn't at all clear in the JavaScript version, and not comments have been added to make it clear.  In most if not all cases, there is a terse comment that says, 'One of sub-states for the attached site', which doesn't really make sense.  The header for each of these should be updated to say which biomolecule(s) the state is used for.

**Comment by aadish** [comment]
fixed, closing
