### ISSUE TITLE
Show Real Cells window is vulnerable to xss

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gene-expression-essentials#62]
Run the sim with `?stringTest=xss`, then click the Show Real Cells button on the third screen to be redirected. Running on current master (4/4 1:30 PM)

**Comment by phet-steele** [comment]
This is no doubt because of the use of `HTMLText` used for italicizing some strings in this window (see https://github.com/phetsims/chains/issues/3#issuecomment-291614197). @aadish is there another way to achieve italicized text without the use of `HTMLText`?

**Comment by jonathanolson** [comment]
Fixed by using RichText (which is new).
