### ISSUE TITLE
protein capture area bounds looks odd when initially created

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#68]
The type `ManualGeneExpressionModel` has the following declaration within it:

```js
    // Rectangle that describes the "protein capture area".  When a protein is dropped by the user over this area, it
    // is considered to be captured.
    this.proteinCaptureArea = new Bounds2( 0, 0, 1, 1 ); // @private
```

This seems like an arbitrary initial value, but the comment doesn't state that.  If that's what it is, it should probably instead be initially set to `Bounds2.NOTHING` and the comment should mention when it gets set.

**Comment by aadish** [comment]
fixed, closing
