### ISSUE TITLE
use step instead of stepInTime

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#69]
Many of the model elements use the function `stepInTime` to advance their state.  This was PhET's convention back in the "Java days", but we generally just use "step" now.  These should be updated.

For the most part, this will be a simple search and replace, but there are some files that have both a `step` and `stepInTime` function.  I looked through these, and at least initially it appears that these should be fairly easy to consolidate.  When doing so, be sure to consider #67.

**Comment by aadish** [comment]
discussed with @jbphet and left the stepInTime functions where play pause functionality is required and removed at other places in above commit

**Comment by aadish** [comment]
fixed, closing
