### ISSUE TITLE
clean up instances of "self" that are not used in closures

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#71]
In the "Coding Style Guidelines" of the "PhET Development Overview" document, it says:

> If references are needed to the enclosing object, such as for a closure, ‘self’ should be used, but it should only be used in closures.  The ‘self’ variable should not be defined unless it is needed in a closure.

I'm seeing some places in the code where `self` is being defined and is *not* being used in closures.  This should be cleaned up.

**Comment by aadish** [comment]
fixed, closing
