### ISSUE TITLE
FlashController should be a separate type

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#73]
The type `FlashController` is defined as an inner type in the file `FlashingShapeNode.js`.  It should be pulled out into a separate file to facilitate reuse and readability.  Also, the parameters `onTime`, `offTime`, `numFlashes`, `flashOnAtStart` and `flashOnAtEnd` should be made into options using PhET's usual options pattern.

**Comment by aadish** [comment]
FlashController has been ported out, leaving this issue open for QA-Testing

**Comment by jbphet** [comment]
I've reviewed and tested the changes, and did some minor cleanup.  This looks good, closing.
