### ISSUE TITLE
Several files in multiple-cells/view are missing comment header at top

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#76]
The comment header that is generally placed at the top of a source code file is missing from several of the types under `multiple-cells/view`.  These should be added.

**Comment by jbphet** [comment]
Also, the JSDoc header for the constructor is missing in many of these files.

**Comment by aadish** [comment]
fixed by commit 1282191f0f26a4031da700c67a13638198b3c7fa
