### ISSUE TITLE
Make BasePairs break when doing Transcription of DNA Molecule

### ISSUE THREAD

**Issue by aadish** [phetsims/gene-expression-essentials#79]
@phet-steele has suggested that it would be nice that break pairs could break as DNA molecule changes when transcribing the DNA molecule. 
This issue is to track this request

**Comment by aadish** [comment]
b9d4b4eedde04c55c9469eaa2522048f9c808411

Implemented this behavior in above commit

@phet-steele can you pull the latest and see if it is desired beahvior

**Comment by jbphet** [comment]
Bumping to high priority.  @phet-steele - please review behavior and comment on whether this behavior is an improvement that should be retained, and if there are any additional changes that you'd recommend.  Once done, please assign back to me and I'll take it from there.  I'll at least need to evaluate the performance and make sure that this doesn't cause any significant degradation over the previous behavior.

**Comment by phet-steele** [comment]
This is great, and a much belated thank you to @aadish!

@jbphet and I discussed a bit ago on an improvement for this. During what we will call the "red twist" (where the red DNA strand originates on top of the turn before being split), the reconnection of base pairs happens well before the strands have settled back into their starting positions. This causes unfortunate layering to occur:
![gee04](https://user-images.githubusercontent.com/5863899/29635669-e3d9617e-880a-11e7-8b61-aca568b4f8fc.gif)

@jbphet proposed to shorten the base pair rectangles during this moment, then re-expand them as the strands move upwards to give the illusion of the red strand passing in front of the base pairs as it "twists".

**Comment by jbphet** [comment]
I fixed this, but blew the commit comment, so the commit is https://github.com/phetsims/gene-expression-essentials/commit/cf9af3a000fcd4181b792ca98e7305715bb5640c.

**Comment by jbphet** [comment]
@phet-steele - please take a look at the version now on master and close if you think the changes cover it.

**Comment by phet-steele** [comment]
@jbphet this is great! There are just small things that are a little weird that I think we could all come to live with. I feel fine to close, thanks.
