### ISSUE TITLE
mRNA is hard to grab

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#81]
The mRNA strand, which can be easily picked up and re-positioned in the Java version of this sim, is hard to grab in the HTML5 simulation, probably because only the line itself is pickable, so it's easy to click on the spaces between the lines.

**Comment by jbphet** [comment]
I've added explicit mouse and touch areas that match the bounds of the mRNA.  This seems to work quite well (thanks @jonathanolson for the suggestion).

Leaving open and unassigned so it can be tested on the next dev or RC release.

**Comment by phet-steele** [comment]
Works great!
