### ISSUE TITLE
Destroyer catches up to polymerase

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/gene-expression-essentials#94]
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS Sierra Version 10.12.6 (16G29)

**Browser:**

Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Problem description:**

If the destroyer catches up to the polymerase, the expression screen stops working. You can't interact with anything in the expression screen. You can click on the other screens and sometimes you can interact with things, and sometimes you can't. Once you've selected another screen, you can't go back to the expression screen. This is for phetsims/QA/issues/58. Found this issue while looking at phetsims/gene-expression-essentials/issues/24.

```
gene-expression-essentials_en.html:990 Uncaught TypeError: Cannot read property 'add' of undefined
    at e.addLength (gene-expression-essentials_en.html:990)
    at e.step (gene-expression-essentials_en.html:990)
    at e.step (gene-expression-essentials_en.html:990)
    at e.step (gene-expression-essentials_en.html:990)
    at gene-expression-essentials_en.html:990
    at Array.forEach (<anonymous>)
    at e.forEach (gene-expression-essentials_en.html:990)
    at e.step (gene-expression-essentials_en.html:990)
    at e.stepSimulation (gene-expression-essentials_en.html:990)
    at e.runAnimationLoop (gene-expression-essentials_en.html:990)
```

**Steps to reproduce:**

1. Go to expression screen.
2. Go to third gene.
3. Add positive transcription factors.
4. Add polymerase.
5. Quickly add destroyer.

**Screenshots:**

![oct-26-2017 10-41-49](https://user-images.githubusercontent.com/31285590/32065576-583ea806-ba3a-11e7-95c1-e7a3672081ae.gif)

**Troubleshooting information (do not edit):**

Name: ‪Gene Expression Essentials‬
URL: https://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.13/gene-expression-essentials_en.html
Version: 1.0.0-dev.13 2017-10-25 21:56:59 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1438x656
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"80b60293","branch":"master"},"babel":{"sha":"ce29f350","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"6b338220","branch":"master"},"dot":{"sha":"85ef2bbf","branch":"master"},"gene-expression-essentials":{"sha":"a8b7efc7","branch":"master"},"joist":{"sha":"eb3a1951","branch":"master"},"kite":{"sha":"2c921cba","branch":"master"},"phet-core":{"sha":"c30d15ed","branch":"master"},"phetcommon":{"sha":"b13138d2","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"92a2872d","branch":"master"},"scenery-phet":{"sha":"d394b9df","branch":"master"},"sherpa":{"sha":"0d590744","branch":"master"},"sun":{"sha":"99a0abef","branch":"master"},"tandem":{"sha":"c1e98f69","branch":"master"}}

**Comment by phet-steele** [comment]
Ribosome can do this too.

**Comment by jbphet** [comment]
Fixed, will have this tested in next dev or RC version.

**Comment by phet-steele** [comment]
Looks fixed.
