### ISSUE TITLE
Some string clean up

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gene-expression-essentials#95]
@jbphet I've done 3 things with the following commits. Please review and approve of the changes.

- ecb9beb941a2d8a1f60a47e3b92f92a9937281a1 Removed quotes from "Collection Complete!"
<img width="365" alt="screen shot 2017-10-26 at 12 32 47 pm" src="https://user-images.githubusercontent.com/5863899/32070628-3df3d948-ba4a-11e7-9194-e266338db3d4.png">

- 6978d9978a17088a46f31261c34b135dae6773af Added a space between "Gene" and it's index for each `GeneNode` on the first screen, eg. was "Gene1" now "Gene 1". I changed this in `DnaMoleculeNode.js` rather than in the strings file so that the space isn't accidentally lost during translation.

<img width="644" alt="screen shot 2017-10-26 at 12 33 04 pm" src="https://user-images.githubusercontent.com/5863899/32070629-3e0bf44c-ba4a-11e7-8acc-5f187a56bec6.png">

- 4ce8ab2e03169868fb06f4b9d3a3982fc67fc49a  Capitalized "slow" and "fast" for the Protein Degradation slider since we use title case for slider labels.
<img width="369" alt="screen shot 2017-10-26 at 12 45 12 pm" src="https://user-images.githubusercontent.com/5863899/32071151-9e0ce2ba-ba4b-11e7-8bac-c99aab53272c.png">

For phetsims/QA/issues/58.

**Comment by phet-steele** [comment]
@jbphet , the more I think about it, we may not need https://github.com/phetsims/gene-expression-essentials/commit/6978d9978a17088a46f31261c34b135dae6773af. `gene` (in the strings file) should just be a pattern.

**Comment by jbphet** [comment]
+1

**Comment by jbphet** [comment]
The first and third changes look good, and I went ahead and made the gene label into a pattern.

**Comment by jbphet** [comment]
This is fixed and reviewed, closing.
