### ISSUE TITLE
Don't let mRNA make connections while dragging

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gene-expression-essentials#97]
Currently, dragging mRNA near a ribosome or destroyer will propose a connection. This proposal persists until the connection occurs, so if the user drags the mRNA away before the connection is made, the ribosome or destroyer will continue to follow (slowly). During this time, NO other biomolecule can interact with the mRNA. This looks quite broken, and can be easily done on accident.

The easy fix would be that no proposals can be made when mRNA is being dragged. Instead the user must release the mRNA first (much like every other biomolecule...).

For phetsims/QA/issues/58.

**Comment by jbphet** [comment]
Fixed, will have this tested in next dev or RC version.

**Comment by phet-steele** [comment]
Looks good.
