### ISSUE TITLE
JILA story - alert AP when close to publication

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gene-expression-essentials#98]
@phet-steele & @jbphet JILA wants to do a story about this simulation (since Tom Perkins is helping fund the conversion and consulting on the sim). They asked to ideally have a few days notice when we think it is getting close to publication. 

Please let me know when you think the sim is 3-5 days out from being published.

**Comment by phet-steele** [comment]
@ariel-phet IT'S SOON!

**Comment by ariel-phet** [comment]
@phet-steele JILA people have been alerted. making the sim live should not depend at all on this story. Closing this issue.
