### ISSUE TITLE
iPad 2 poor performance

### ISSUE THREAD

**Issue by BryceAG** [phetsims/gene-expression-essentials#99]
All sections of the sim can easily be brought to having 5 FPS. For Expression just creating RNA with polymerase will drop the frame rate down to 10 FPS, and if you pull out a couple of the Biomolecules for each gene it will drop to 5. With mRNA just raising the concentration of the Positive Transcription Factor to High will drop the frame rate to ~6-8, and adding some negative Transcription Factor will drop it to 5. and for Multiple Cells, without changing anything else, just going to "many" cells will drop the frame rate to 5.

I know that poor performance is probably expected with iPad 2, but it is fairly easy to get this low of a frame rate. Related to phetsims/QA#58

**Comment by phet-steele** [comment]
Duplication police has arrived! Copying this into #55.
